### ISSUE TITLE
Errors changing from "Only Navigation Bars" profile

### ISSUE THREAD

**Issue by SrNetoChan** [boundlessgeo/qgis-profiles-plugin#4]
After using "Only Navigation Bars" Profile, trying to use the other two will throw errors. Applying the other profiles without having used the "Only Navigation Bars" works as expected.

```
2016-06-01T11:37:02	1	Traceback (most recent call last):
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 306, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "/home/alexandre/.qgis2/python/plugins/geoserverexplorer/__init__.py", line 16, in classFactory
			    return GeoServerExplorerPlugin(iface)
			  File "/home/alexandre/.qgis2/python/plugins/geoserverexplorer/plugin.py", line 29, in __init__
			    self.provider = GeoServerProvider()
			  File "/home/alexandre/.qgis2/python/plugins/geoserverexplorer/processingprovider/geoserverprovider.py", line 28, in __init__
			    UploadVector(),
			  File "/usr/share/qgis/python/plugins/processing/core/GeoAlgorithm.py", line 52, in __init__
			    self._icon = QIcon(os.path.dirname(__file__) + '/../images/alg.png')
			AttributeError: 'NoneType' object has no attribute 'path'
			
2016-06-01T11:37:02	1	Traceback (most recent call last):
			  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 306, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "/home/alexandre/.qgis2/python/plugins/QuickOSM/__init__.py", line 28, in classFactory
			    return QuickOSM(iface)
			  File "/home/alexandre/.qgis2/python/plugins/QuickOSM/quick_osm.py", line 83, in __init__
			    self.provider = QuickOSMAlgorithmProvider()
			  File "/home/alexandre/.qgis2/python/plugins/QuickOSM/quick_osm_processing/algorithm_provider.py", line 52, in __init__
			    OverpassQueryGeoAlgorithm(),
			  File "/usr/share/qgis/python/plugins/processing/core/GeoAlgorithm.py", line 52, in __init__
			    self._icon = QIcon(os.path.dirname(__file__) + '/../images/alg.png')
			AttributeError: 'NoneType' object has no attribute 'path'
```

**Comment by alexbruy** [comment]
Seems already fixed in master
